### ISSUE TITLE
Lỗi Không Gõ Được Trên Thanh Search

### ISSUE THREAD

**Issue by kimeulug** [BambooEngine/ibus-bamboo#167]
Em cài Ibus-Unikey thì bị lỗi không gõ được Tiếng Việt nên qua Ibus-BamBoo nhưng tiếc là vẫn bị lỗi, cụ thể như sau:
- Em gõ ở text editor thì vẫn bình thường
- Gõ trên FB hay PỵCharm đều ổn
- Gõ ở mục search của Chrome hoặc Firefox thì không gõ được

Hiện tại em đang dùng Kali Linux 2020.3. Mong được các anh chị giúp đỡ ạ.

**Comment by luongthanhlam** [comment]
bạn đã làm theo các hướng dẫn ở đây chưa? https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60

**Comment by kimeulug** [comment]
`gpg: keybox '/tmp/tmp38_agc88/pubring.gpg' created
gpg: /tmp/tmp38_agc88/trustdb.gpg: trustdb created
gpg: key 36ED424E9659D014: public key "Launchpad PPA for bamboo-engine" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.8/shutil.py", line 672, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 670, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.browser'
`
Em cảm ơn anh đã rep, em cài lại thì bị lỗi này ạ

**Comment by kimeulug** [comment]
Em da thu moi cach cho wiki ma van khong the khac phuc duoc. Anh co the ho tro em voi duoc khong a. Em cam on anh nhieu a.

**Comment by luongthanhlam** [comment]
em cài bằng cách nào? em thử cài từ file deb chưa https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo#directUbuntu

**Comment by luongthanhlam** [comment]
Fixed: https://github.com/BambooEngine/ibus-bamboo/commit/cc6a7589f4481827e62d9ab814b2c7a906d47645
