### ISSUE TITLE
Lỗi không gõ được Tiếng Việt trên ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by KingNNT** [BambooEngine/ibus-bamboo#300]
**Mô tả lỗi**
Hiện tại mình chưa rõ lý do vì sao không gõ được tiếng Việt tại ubuntu 20.04. Mình có 1 máy có quyền root thì mình gõ bình thường, 1 máy khác mình không có quyền root, thì khi cài xong không gõ được.
Mình có xem qua thấy trùng với #127, nhưng không rõ cách khắc phục.
Mình có thử cài lại cũng không được, nhưng khi chuyển qua dùng ibus-unikey thì lại được.

**Các bước tái hiện lỗi**
Hiện tại mình không thể gõ trên bất kì ứng dụng nào, 
Khi vào Setting > Region & Language > Input sources. Tại option Vietnamese(Bamboo) mình nhấn vào nút option cũng không hiện lên gì cả.
Trong issue #127 mình check thử file config.json thì không có file này (Mình không rõ là update lên bản mới đã bỏ nó đi, hay do quá trình cài đặt bị lỗi nên không có, nhưng khi cài đặt thì mình không nhận được thông báo lỗi gì trên terminal).

Khi chạy `ibus engine Bamboo`  kết quả trả ra là:
```
(process:22226): IBUS-CRITICAL **: 11:07:48.632: ibus_bus_set_global_engine: assertion 'IBUS_IS_BUS (bus)' failed
Set global engine failed.
```

Khi chạy với `ibus-deamon -xrv` kết quả trả ra là:
```
goroutine 1 [running]:
github.com/BambooEngine/goibus/ibus.NewBus.func1(...)
	/build/ibus-bamboo-iLFv5I/ibus-bamboo-0.8.0/src/github.com/BambooEngine/goibus/ibus/bus.go:16
github.com/BambooEngine/goibus/ibus.NewBus(0x6f1de0)
	/build/ibus-bamboo-iLFv5I/ibus-bamboo-0.8.0/src/github.com/BambooEngine/goibus/ibus/bus.go:21 +0x321
main.main()
	/build/ibus-bamboo-iLFv5I/ibus-bamboo-0.8.0/src/ibus-bamboo/main.go:64 +0x484

```

Khi chạy với `ibus-deamon -rv` kết quả trả ra là:
```
panic: dial unix @/home/tuannn%40kaopiz.local/.cache/ibus/dbus-LFXUrMlk: connect: connection refused

goroutine 1 [running]:
github.com/BambooEngine/goibus/ibus.NewBus.func1(...)
	/build/ibus-bamboo-iLFv5I/ibus-bamboo-0.8.0/src/github.com/BambooEngine/goibus/ibus/bus.go:16
github.com/BambooEngine/goibus/ibus.NewBus(0x6f1de0)
	/build/ibus-bamboo-iLFv5I/ibus-bamboo-0.8.0/src/github.com/BambooEngine/goibus/ibus/bus.go:21 +0x321
main.main()
	/build/ibus-bamboo-iLFv5I/ibus-bamboo-0.8.0/src/ibus-bamboo/main.go:64 +0x484


```

**Môi trường**
 - OS và version: Ubuntu 20.04.3 LTS
 - Desktop: mặc định
 - Phiên bản ibus-bamboo: 0.8.0 (Bản mới nhất hiện tại)

**Comment by luongthanhlam** [comment]
bạn đang dùng Ubuntu trong môi trường Wayland hay X11?
```
echo $XDG_SESSION_TYPE
```

**Comment by KingNNT** [comment]
> 

Hiện tại mình đang dùng x11

**Comment by luongthanhlam** [comment]
bạn thử chạy lệnh này rồi gửi mình ouput nhé
```
echo $IBUS_ADDRESS
echo $IBUS_ADDRESS_FILE
```

**Comment by KingNNT** [comment]
> 

Mình chạy nó đều ra trống cả, cả 2 variable đó luôn

**Comment by luongthanhlam** [comment]
ok, bạn chạy thêm giúp mình mấy lệnh này nữa nhé
```
cat /var/lib/dbus/machine-id
cat /etc/machine-id
ls ~/.config/ibus/bus/
cat $(ls ~/.config/ibus/bus/)
```

**Comment by luongthanhlam** [comment]
`tuannn%40kaopiz.local` có phải là user bạn đang dùng không?

**Comment by KingNNT** [comment]
> ok, bạn chạy thêm giúp mình mấy lệnh này nữa nhé
> 
> ```
> cat /var/lib/dbus/machine-id
> cat /etc/machine-id
> ls ~/.config/ibus/bus/
> cat $(ls ~/.config/ibus/bus/)
> ```

Để sang tuần mình sẽ chạy thử các lệnh kia xem sao, user kia đúng là cái mình đang dùng, nhưng để đảm bảo thông tin thì bạn xoá reply phía trên giúp mình được không ?

**Comment by KingNNT** [comment]
> `tuannn%40kaopiz.local` có phải là user bạn đang dùng không?

Đúng là mình đang dùng nó, để sang tuần mình thử chạy thêm lệnh kia xem sao

**Comment by KingNNT** [comment]
![image](https://user-images.githubusercontent.com/38956244/144776676-27691ee1-70b3-4fe7-ab70-b64625a7596a.png)

Mình chạy xong nó báo như thế này bạn ạ.

**Comment by luongthanhlam** [comment]
Khi chạy `ibus-daemon -xrd` thì ibus sẽ tạo 1 file chứa địa chỉ socket trong thư mục `~/.config/ibus/bus` với quyền `0664`, có vẻ tài khoản của bạn không có quyền đọc file trong thư mục này 🤔

**Comment by KingNNT** [comment]
![image](https://user-images.githubusercontent.com/38956244/144957468-98c9026a-d34b-4607-95a4-4ab8ee9b2bfa.png)

Có vẻ lỗi do account mình không đủ quyền thật, nếu mà bây giờ mình `chmod` cho thư mục `~/.config/ibus/bus` thì có khả thi hơn không nhỉ.

**Comment by luongthanhlam** [comment]
> ![image](https://user-images.githubusercontent.com/38956244/144957468-98c9026a-d34b-4607-95a4-4ab8ee9b2bfa.png)
> 
> Có vẻ lỗi do account mình không đủ quyền thật, nếu mà bây giờ mình `chmod` cho thư mục `~/.config/ibus/bus` thì có khả thi hơn không nhỉ.

mình nghĩ là được, có thể test bằng cách chạy lệnh `cat $(ls ~/.config/ibus/bus/)`

**Comment by KingNNT** [comment]
> > ![image](https://user-images.githubusercontent.com/38956244/144957468-98c9026a-d34b-4607-95a4-4ab8ee9b2bfa.png)
> > Có vẻ lỗi do account mình không đủ quyền thật, nếu mà bây giờ mình `chmod` cho thư mục `~/.config/ibus/bus` thì có khả thi hơn không nhỉ.
> 
> mình nghĩ là được, có thể test bằng cách chạy lệnh `cat $(ls ~/.config/ibus/bus/)`

Mình có thử cả với `0664` và `777` cho folder `~/config/ibus/bus` và các file bên trong nó nhưng vẫn không được.

**Comment by luongthanhlam** [comment]
lỗi như thế nào nhỉ?
```
ls -l ~/.config/ibus/bus/
cat $(ls ~/.config/ibus/bus/)
ibus-daemon -xdr
```

**Comment by KingNNT** [comment]
> 

![image](https://user-images.githubusercontent.com/38956244/145012109-f50f9f82-4ad1-43dd-a4c1-7aafee52d3ed.png)
Mình có chạy thử xong nó ra như thế này, lỗi của mình bên trên ý là vẫn không thể gõ tiếng Việt được với bamboo ý.

**Comment by phananhnhat** [comment]
Minh cung dan gap loi tuong tu

**Comment by luongthanhlam** [comment]
có cách nào tái hiện không nhỉ? mình thử với user khác thì vẫn hoạt động bình thường

**Comment by anhnt-2136** [comment]
@luongthanhlam mình cũng gặp lỗi tương tự và cũng tên ubuntu 20.04, ibus-bamboo đang là latest. Khi cài đặt và chuyển sang ibus-bamboo xong thì không gõ được tiếng Việt và phần option của ibus-bamboo cũng không bật lên được

**Comment by luongthanhlam** [comment]
@anhnt-2136 @KingNNT  bạn có thể tái hiện trên máy ảo không? nếu có thì export gửi mình nhé

**Comment by hmthang96** [comment]
mình cũng gặp lỗi tuơng tự thế này. 
Cài đặt xong không gõ đuợc, không mở đuợc setting của bamboo và khi chuyển từ en sang vi bamboo thì bị delay khoảng 2s 5s xong moiws bắt đầu gõ đuợc. 
Tình trạgn xảy ra ở các máy ubuntu đăng nhập user bằng domain

**Comment by nghiadxvn** [comment]
minh gap loi y het hmthang96.
Neu minh cd truc tiep vao thu muc ~/.config/ibus/bus/ sau do chay lenh cat $(ls ~/.config/ibus/bus/) se duoc
Nhung neu o thu muc hien tai chay lenh cat $(ls ~/.config/ibus/bus/) thi se loi `cat: 7a636ee9a371482bab983ba333ca63e5-unix-0: No such file or directory`

**Comment by t1ld3x** [comment]
@nghiadxvn bạn có thể tái hiện lỗi này trên máy ảo ko? hiện tại  mình chưa tìm ra cách nào tái hiện lỗi này

**Comment by nghiadxvn** [comment]
minh khong dung may ao ban
