### ISSUE TITLE
ubuntu 22.04, has internet connection but got TimeoutError: [Errno 110] Connection timed out when add-apt-repo

### ISSUE THREAD

**Issue by longtth** [BambooEngine/ibus-bamboo#376]
**Mô tả lỗi**

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở terminal 
2. Gõ `sudo add-apt-repository ppa:bamboo-engine/ibus-bamboo` 
3. Got this error: 
```
longnx@ub2004:~$ sudo add-apt-repository ppa:bamboo-engine/ibus-bamboo
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 347, in main
    shortcut = handler(source, **shortcut_params)
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 82, in __init__
    if self.lpppa.publish_debug_symbols:
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 107, in lpteam
    self._lpteam = self.lp.people(self.teamname)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 98, in lp
    self._lp = login_func("%s.%s" % (self.__module__, self.__class__.__name__),
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 494, in login_anonymously
    return cls(
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 230, in __init__
    super(Launchpad, self).__init__(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 472, in __init__
    self._wadl = self._browser.get_wadl_application(self._root_uri)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 447, in get_wadl_application
    response, content = self._request(url, media_type=wadl_type)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 389, in _request
    response, content = self._request_and_retry(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 359, in _request_and_retry
    response, content = self._connection.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 144, in _request
    response, content = super(LaunchpadOAuthAwareHttp, self)._request(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 184, in _request
    return super(RestfulHttp, self)._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1363, in _conn_request
    conn.connect()
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1153, in connect
    sock.connect((self.host, self.port))
TimeoutError: [Errno 110] Connection timed out
```
**Kết quả mong muốn**

repo got added and I can `sudo apt update` and install ibus-bamboo 

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version:  Ubuntu 22.04
 - Desktop: **default** 
 - Phiên bản ibus-bamboo: latest

**Thông tin thêm**

Fresh install

**Comment by luongthanhlam** [comment]
bạn kiểm tra lại kết nối mạng/firewall xem
```
ping ppa.launchpad.net
```

**Comment by longtth** [comment]
> bạn kiểm tra lại kết nối mạng/firewall xem
> 
> ```
> ping ppa.launchpad.net
> ```

cám ơn bạn đã trả lời, hôm nay mình thử lại với 2 lệnh 

```
sudo add-apt-repository ppa:bamboo-engine/ibus-bamboo
sudo apt install ibus-bamboo -y
```

thì được rồi :D 
chẳng hiểu bị gì :D
