### ISSUE TITLE
Kích hoạt bộ gõ tiếng Việt gây crash Opera

### ISSUE THREAD

**Issue by romhunter** [BambooEngine/ibus-bamboo#46]
Nếu mở trình duyệt Opera lên trong khi ibus-bamboo đang kích hoạt (gõ tiếng Việt) thì Opera sẽ bị crash liên tục, không thể tắt, không thể vào web. Nếu muốn thao tác trên Opera thì phải chuyển ibus qua English, sau đó thực hiện. Ví dụ mở website trước, sau đó chuyển ibus qua tiếng Việt thì mới gõ được.

Nếu mới mở Opera + để ibus tiếng Việt thì crash liên tục, thậm chí tắt chương trình đi thì nó cũng mở lại và báo đã crash. 

Khi gõ tiếng Việt thì cũng có hiển thị gạch chân ở dưới, nếu click vô ô fix gạch chân thì khỏi viết tiếng Việt luôn :) 

Hiện tại thì hệ thống của mình như sau:
 - OS: Ubuntu 18.04
 - Desktop: mặc định
 - Phiên bản ibus: 1.5.17
 - Phiên bản ibus-bamboo: mới nhất
 - Phiên bản Opera: mới nhất

**Comment by auduongtansang** [comment]
Mình đang gặp lỗi tương tự trên Google Chrome lẫn Chromium với Elementary OS Juno (Ubuntu 18.04)

**Comment by romhunter** [comment]
vậy có thể là lỗi liên quan tới nhân Chromium nhỉ? Opera hiện tại cũng sử dụng nhân Chromium.

**Comment by ndgnuh** [comment]
Mình không tái hiện được lỗi trên `chromium`. Đây là log khi bật `chromium` (không bị crash hay gì, dùng bình thường)

```sh
[19987:19987:0618/213250.601708:ERROR:sandbox_linux.cc(368)] InitializeSandbox() called with multiple threads in process gpu-process.
[19987:19987:0618/213250.744636:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

(chromium:19960): IBUS-WARNING **: 21:33:01.097: chromium has no capability of surrounding-text feature
# Cái warning xảy ra khi gõ chữ, mình xóa bớt đi cho gọn

(chromium:19960): IBUS-WARNING **: 21:33:01.400: chromium has no capability of surrounding-text feature
[19960:19969:0618/213301.589410:ERROR:browser_process_sub_thread.cc(217)] Waited 14 ms for network service
```

Đây là log khi bật `opera`
```sh
[18822:18822:0618/213120.487163:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[18795:18795:0618/213121.060102:ERROR:CONSOLE(0)] "Unchecked runtime.lastError while running operaTouchPrivate.getLocalName: Cannot obtain local name
    at chrome-extension://ebongfbmlegepmkkdjlnlmdcmckedlal/touch_communication.js:250:35", source: chrome-extension://ebongfbmlegepmkkdjlnlmdcmckedlal/page.html (0)
[18795:18795:0618/213123.757273:ERROR:named_platform_channel_posix.cc(145)] connect /home/hung/.config/opera/oauc_pipe_r: Connection refused (111)
[18795:18795:0618/213123.757499:ERROR:ipc_service_impl.cc(167)] [AU] Couldn't create /home/hung/.config/opera/oauc_pipe_r pipe client
[19334:19334:0618/213125.561970:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[19287:19287:0618/213126.123371:ERROR:CONSOLE(0)] "Unchecked runtime.lastError while running operaTouchPrivate.getLocalName: Cannot obtain local name
    at chrome-extension://ebongfbmlegepmkkdjlnlmdcmckedlal/touch_communication.js:250:35", source: chrome-extension://ebongfbmlegepmkkdjlnlmdcmckedlal/page.html (0)

(opera:19287): IBUS-WARNING **: 21:31:27.361: opera has no capability of surrounding-text feature

(opera:19287): IBUS-WARNING **: 21:31:27.412: opera has no capability of surrounding-text feature

(opera:19287): IBUS-WARNING **: 21:31:27.520: opera has no capability of surrounding-text feature
[19287:19287:0618/213128.855002:ERROR:named_platform_channel_posix.cc(145)] connect /home/hung/.config/opera/oauc_pipe_r: Connection refused (111)
[19287:19287:0618/213128.855145:ERROR:ipc_service_impl.cc(167)] [AU] Couldn't create /home/hung/.config/opera/oauc_pipe_r pipe client
Discarded=1
```

Mình chỉ *đoán mò* thôi, bạn vào phần cài đặt và tắt thử một vài tính năng xem hết lỗi không :))

**Comment by romhunter** [comment]
"Tính năng" duy nhất khác mặc định mà mình bật trên Opera là Dark Mode (lol), để mai mình sẽ test lại và upload log lên xem sao.

**Comment by romhunter** [comment]
Đây là log của mình khi bật `Opera` và có enable `ibus-bamboo`:

```shell
rom@ROM:~$ opera&
[1] 7008
rom@ROM:~$ [7036:7036:0619/102923.943250:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[7008:7008:0619/102924.722259:ERROR:CONSOLE(0)] "Unchecked runtime.lastError while running operaTouchPrivate.getLocalName: Cannot obtain local name
    at chrome-extension://ebongfbmlegepmkkdjlnlmdcmckedlal/touch_communication.js:250:35", source: chrome-extension://ebongfbmlegepmkkdjlnlmdcmckedlal/page.html (0)
[7744:7744:0619/102926.847456:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[7709:7709:0619/102927.647466:ERROR:CONSOLE(0)] "Unchecked runtime.lastError while running operaTouchPrivate.getLocalName: Cannot obtain local name
    at chrome-extension://ebongfbmlegepmkkdjlnlmdcmckedlal/touch_communication.js:250:35", source: chrome-extension://ebongfbmlegepmkkdjlnlmdcmckedlal/page.html (0)
Discarded=1
[1]+  Segmentation fault      (core dumped) opera
```

Còn đây là log khi không bật `ibus-bamboo`:
```shell
rom@ROM:~$ [8841:8841:0619/103303.577109:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[8814:8814:0619/103304.392730:ERROR:CONSOLE(0)] "Unchecked runtime.lastError while running operaTouchPrivate.getLocalName: Cannot obtain local name
    at chrome-extension://ebongfbmlegepmkkdjlnlmdcmckedlal/touch_communication.js:250:35", source: chrome-extension://ebongfbmlegepmkkdjlnlmdcmckedlal/page.html (0)
[1]+  Done                    opera
```

Mình cũng đã test restore default settings mà vẫn k ổn, trình duyệt vẫn cứ crash ầm ầm :(

**Comment by van26101998** [comment]
Mình cũng bị crash trên brave và chrome.
<strong>Sau khi tắt tính năng theo dõi chuột thì không bị nữa.</strong>
Cứ bật theo dõi chuột thì bị>

**Comment by luongthanhlam** [comment]
đã tìm ra nguyên nhân, mọi người cập nhật lên bản v0.5.0 để sửa lỗi này nhé.

**Comment by romhunter** [comment]
All fixed, close nhé. Thanks bên dev.
